:toclevels: 5
:sectnums:

[ComputerComponents]
= コンピュータの構造

[[ComputerComponents_Overview]]
== Overview
システム開発の多くの作業はコンピュータ上で行われる。 +
本節ではそのコンピュータがどういった構造になっているかを解説する。 +

[[ComputerComponents_Type]]
== コンピュータの種類
大きなくくりでコンピュータといった場合、構造や用途によっていくつかの種類が存在する。 +
実務上PC,サーバの事がわかっていれば問題ないが、基礎知識として以下にコンピュータの種類を示す。 +
なお、PCをサーバのように使用するなど区別が明確に決まっていない場合もある。 +

[[ComputerComponents_Type_Table]]
.コンピュータの種類
[cols="30,70", options="header"]
|===
|名称
|概要

|PC(パーソナルコンピュータ)
|個人が占有して使用するコンピュータ  +
デスクトップやノートパソコンなどはほぼここに当てはまる

|ワークステーション
|CADやCG、科学計算などで主に利用する高性能のPCを指す  +
PCの性能上昇に伴い区別は曖昧である

|サーバ
|ファイルの配信やWebページの配信など、何らかのサービスを配信する機能を持つコンピュータ  +
デスクトップ型からラック型まで様々な種類があるが、高負荷や連続稼働に耐えられるようなCPUやUPS(無停電装置)を備えていることが多い  +
また、サービス提供用のソフトウェアをインストールしている。

|メインフレーム
|主に大きな組織の基幹業務で大量のデータを取り扱うコンピュータ  +
以前は主流であったが徐々に数を減らしている

|スーパーコンピュータ
|科学計算など高速に計算を行うことを目的にしたコンピュータ

|マイクロコンピュータ
|各家電や車、携帯電話などに組み込まれている小型のコンピュータ  +

|シーケンサ
|工業機械の制御などに用いられる専用のコンピュータ
|===

[[ComputerComponents_Component]]
== コンピュータの構成要素

コンピュータを構成する基本的な要素をハードウェアとソフトウェアに分けて大雑把に解説する。

[[ComputerComponents_Component_Overview]]
=== ハードウェア
コンピュータは様々なハードから構成されている。 +
非常に大雑把ではあるが、コンピュータの全体構成と各種処理の流れを以下の図に示す。

//図を挿入する


各装置の概要を以下に示す。

.ハードウェアの種類
[cols="30,20,50", options="header"]
|===
|名称
|代表例
|概要

|入力装置
|キーボード、マウス
|コンピュータに対し、何らかの指示を与えるための装置

|出力装置
|スピーカ、モニタ
|コンピュータの指示によって人間に認識できる形で何らかの出力を行う装置

|補助記憶装置
|HDD、SSD
|電源がなくてもデータを維持できる大容量の記憶装置  +
記憶容量辺りの単価も主記憶装置と比較して安い

|主記憶装置
|DRAM
|中央処理装置と高速にデータをやりとりできる記憶装置  +
電源が切れるとデータは消える

|中央処理装置
|CPU
|演算を行う演算装置、各機器を制御する制御装置、および演算などに利用するデータ保存領域であるレジスタなどをまとめた装置
|===

システム開発の現場では、直接上記の構成を意識することはない。  +
ただし、CPUやメモリのスペックなどはシステムの安定性や性能に直結するため、設計や性能試験で考慮する必要がある。  +
詳細は<<>>を参照のこと

[[ComputerComponents_Component_Software]]
=== ソフトウェア
コンピュータは上記ハードウェアで構成されるが、ハードウェアを制御/操作するソフトウェアがなければ動作しない。
ソフトウェアの構成とハードウェアとの連携方法を以下の図に示す。

//図を置く

各ソフトウェアの概要を以下に示す。

.ソフトウェアの種類
[cols="30,20,50", options="header"]
|===
|名称
|代表例
|概要

|アプリケーションソフトウェア
|Excel、Word
|主に直接ユーザが利用することになるプログラム  +
システム開発で作成する成果物も主にここのレイヤになる。  +
OSの上で機能し、直接ハードウェアを操作することはない。

|OS
|Windows、Mac、Ubuntu
|アプリケーションソフトウェアの土台となるソフトウェア  +
OSはカーネルを内包し、その他にシェルやデバイスドライバなどを含む。  +

|カーネル
|Windowsカーネル、Linuxカーネル
|ハードウェアを制御する事ができるレイヤに位置するソフトウェア  +
ユーザが直接利用することはできず、シェルなどを通してカーネルに指示を出すことでハードウェアを間接的に操作する。
|===


[[ComputerComponents_Component_OS]]
==== OS
前述したように、OSはハードウェアを制御するカーネルを核とし、ユーザにGUI環境を提供する機能や、カーネルとやり取りを行う窓口となるシェル、その他色々なソフトウェアをひとまとめにしたもので成り立っている。  +
当然その構成によって様々な種類のOSが存在し、機能に差異があることから、システム開発の現場では開発環境および動作環境がどのOSになるかを意識する必要がある。  +
どういった種類のOSがあるか、以下にピックアップして示す。  +
なお、分類については諸説あるため、大まかな分類であると認識していただきたい。

.OSの種類
[cols="30,70", options="header"]
|===
|名称
|概要

|Windows
|世界のデスクトップPCで大きなシェアを持つOS  +
動作環境はともかく、開発環境はWindowsであることが多い傾向にある  +
後述するMac/Unix/Linux系のOSとは大きく異なるため、Dockerがデフォルトではうまく動作しないなど開発するにあたり障害となる場合もある。

|Mac
|後述するUnix系OSから派生して作られたOS  +
元がUnixなため、Unixで使用できるシェルなどが使える。

|Unix系OS
|AT＆Tが開発したUNIXを基本の仕様としてもつOS群  +
AIXやHP-UX、Solarisなどが存在する。  +
後述するLinuxはその経緯からUNIXライクなOSとされるためUnixではない。

|Linux系OS
|オープンソースのカーネルであるLinuxカーネルを核として持つOS群  +
オープンソースであるため、各ユーザが望む機能を追加して、OSとして配布している。この各OSのことをディストリビューションと呼ぶ。  +
有名なディストリビューションとしてはDebian系、RedHat系と呼ばれるものがあり、さらにその中でもUbuntuやRHELなどで細かく分けられる。  +

|モバイル系OS
|AndroidやiOSなどスマートフォン上で動作するOS  +
モバイル系の中でもAndroidはLinuxから派生したなど様々な違いがあるが、本ガイドラインでは取り扱わない。  

|サーバ系OS
|Windows ServerやLinux/Unix系OSなど、サーバに必要な機能である多数の接続要求や安定性を高めたOSを指す。  +
開発したWebアプリケーションなどはこれらのOS上で動作することが多い。
|===

[[ComputerComponents_Component_VM]]
==== 仮想環境