:toclevels: 5
:sectnums:

[ProgramExecution]
= プログラムの実行

[[ProgramExecution_Overview]]
== Overview
本節では、記述したプログラムコードがどのように実行されるのかを解説する。  +

[[ProgramExecution_Code]]
== コード

ある特定のルールに従って記述され、コンピュータに解釈させる、もしくは何らかの動作を実行させることを目的として作成されたデータをコード(プログラムコード/ソースコード)と呼ぶ。  +
前節で述べたように、ハードウェアの領域では二進数で取り扱われるため、基本的には最終的に後述のネイティブコードでハードウェアに伝える必要がある。  +
当然二進数なため人間が直接解釈/記述するのは非常に難しい。そのため、通常は人間が解釈しやすい高水準言語を読み書きし、様々なツールを利用してネイティブコードに変換する方式をとる。 +
人間が解釈しやすい高水準言語に対して、ネイティブコードに近いものを低水準言語と呼ぶ。 +
以下に概要図を示す。  +

[[ProgramExecution_Code_Low-LevelLang]]
=== 低水準言語
前述したように、機械が解釈できる二進数で書かれたネイティブコード、またネイティブコードに近い形式であるアセンブリ言語などは低水準言語と呼ばれる。  +
実務的にはアセンブリ言語はともかくネイティブコードを直接取り扱うことはないと思われる。

[[ProgramExecution_Code_Low-LevelLang_Native]]
==== ネイティブコード
CPUなどに直接命令を指示できるような二進数もしくは人間により理解できるように16進数で記述されたコードをネイティブコードもしくは機械語と呼ぶ。  +
ネイティブコードは基本的にCPUに対する命令の部分とデータ部分もしくは命令で操作される対象から成り立ち、命令の部分はCPUの種類によって仕様が異なるため種類の異なるCPUでは同じコードでも実行されることが異なる。  +
この命令の仕様を**命令セット**と呼び、命令のことを**オペコード**、オペコードによって操作される対象を**オペランド**と呼ぶ。  +
汎用のCPUの多くが採用しているx86-64系のネイティブコードの仕様は https://software.intel.com/en-us/articles/intel-sdm[intel] のwebページ上で公開されている。  +

これらのコードは必ずしもハードウェアで実行されるものだけではなく、Java VMなどに代表される仮想マシン上で実行されるものも存在する。

[[ProgramExecution_Code_Low-LevelLang_Assembly]]
==== アセンブリ言語


[[ProgramExecution_Code_High-LevelLang]]
=== 高水準言語

[[ProgramExecution_Code_Language_Compiler]]
==== コンパイラ言語

[[ProgramExecution_Code_Language_Interpreter]]
==== スクリプト言語

[[ProgramExecution_Code_Language_Others]]
==== その他

== プログラムの起動



